'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const {
  getTierPolicyFromThemeSettings,
  resolveCustomerTier,
  resolveProductDiscount
} = require('../lib/tier-pricing-policy');
const {
  mergePublishedThemeSettings
} = require('../lib/theme-settings');

const schema = JSON.stringify([{
  name: 'Tier Pricing',
  settings: [
    { type: 'checkbox', id: 'tier_pricing_enabled', default: true },
    { type: 'select', id: 'tier_pricing_scope', default: 'all' },
    { type: 'text', id: 'tier_1_name', default: 'BLACK DIAMOND' },
    { type: 'text', id: 'tier_1_tag', default: 'BLACK DIAMOND' },
    { type: 'range', id: 'tier_1_discount', default: 10 },
    { type: 'text', id: 'tier_1_threshold', default: '100000000' },
    { type: 'range', id: 'tier_2_discount', default: 8 },
    { type: 'text', id: 'tier_2_threshold', default: '20000000' },
    { type: 'range', id: 'tier_3_discount', default: 6 },
    { type: 'text', id: 'tier_3_threshold', default: '10000000' },
    { type: 'range', id: 'tier_4_discount', default: 4 },
    { type: 'text', id: 'tier_4_threshold', default: '6000000' },
    { type: 'range', id: 'tier_5_discount', default: 2 },
    { type: 'text', id: 'tier_5_threshold', default: '3000000' },
    { type: 'range', id: 'tier_6_discount', default: 0 },
    { type: 'checkbox', id: 'tier_prioritize_tags', default: true },
    { type: 'checkbox', id: 'tier_use_custom_metafield', default: true }
  ]
}]);

test('parser accepts Shopify comments and trailing commas', () => {
  const settings = mergePublishedThemeSettings(
    '/* generated */\n{"current":{"tier_1_discount":11,},}',
    '[{"settings":[{"id":"tier_1_discount","default":10,},],},]'
  );

  assert.equal(settings.tier_1_discount, 11);
});

test('published settings override schema defaults', () => {
  const data = `/* generated by Shopify */\n${JSON.stringify({
    current: {
      tier_2_discount: 9,
      tier_2_threshold: '25000000',
      unrelated_setting: 'ignored'
    }
  })}`;
  const settings = mergePublishedThemeSettings(data, schema);

  assert.equal(settings.tier_1_discount, 10);
  assert.equal(settings.tier_2_discount, 9);
  assert.equal(settings.tier_2_threshold, '25000000');
  assert.equal(settings.unrelated_setting, undefined);
});

test('policy uses the per-tier percentages from Theme Editor', () => {
  const data = JSON.stringify({
    current: {
      tier_1_discount: 12,
      tier_2_discount: 9,
      tier_3_discount: 7,
      tier_4_discount: 5,
      tier_5_discount: 3,
      tier_6_discount: 1,
      tier_prioritize_tags: true
    }
  });
  const settings = mergePublishedThemeSettings(data, schema);
  const policy = getTierPolicyFromThemeSettings(settings, {});

  assert.deepEqual(
    policy.tiers.map(tier => tier.discount),
    [12, 9, 7, 5, 3, 1]
  );
  assert.equal(
    resolveCustomerTier({ tags: ['DIAMOND'], amountSpent: { amount: '0' } }, policy).discount,
    9
  );
});

test('custom spend metafield setting matches Theme Editor behavior', () => {
  const data = JSON.stringify({
    current: {
      tier_prioritize_tags: false,
      tier_use_custom_metafield: false
    }
  });
  const settings = mergePublishedThemeSettings(data, schema);
  const policy = getTierPolicyFromThemeSettings(settings, {});
  const tier = resolveCustomerTier({
    tags: [],
    totalSpentMetafield: { value: '999999999' },
    amountSpent: { amount: '4000000', currencyCode: 'VND' }
  }, policy);

  assert.equal(tier.name, 'SILVER');
});

test('disabled tier pricing returns no product discount', () => {
  const settings = mergePublishedThemeSettings(
    JSON.stringify({ current: { tier_pricing_enabled: false } }),
    schema
  );
  const policy = getTierPolicyFromThemeSettings(settings, {});

  assert.equal(policy.enabled, false);
  assert.equal(
    resolveProductDiscount(
      policy.tiers[0],
      ['tier-blackdiamond-99'],
      ['all-products'],
      policy
    ),
    0
  );
});
